-- Initial data for Host Management System
-- Run this after package installation to populate lookup tables

-- Guest Types (Tipo Alloggiato) - Official Italian codes
INSERT INTO host.guest_type (code, description) VALUES
('16', 'OSPITE SINGOLO'),
('17', 'CAPO FAMIGLIA'),
('18', 'CAPO GRUPPO'),
('19', 'FAMILIARE'),
('20', 'MEMBRO GRUPPO')
ON CONFLICT DO NOTHING;

-- Document Types - Official Italian document codes (96 types)
INSERT INTO host.document_type (code, description) VALUES
('IDENT', 'CARTA DI IDENTITA'''),
('CIDIP', 'CARTA ID. DIPLOMATICA'),
('IDELE', 'CARTA IDENTITA'' ELETTRONICA'),
('CERID', 'CERTIFICATO D''IDENTITA'''),
('PASSE', 'PASSAPORTO DI SERVIZIO'),
('PASDI', 'PASSAPORTO DIPLOMATICO'),
('PASOR', 'PASSAPORTO ORDINARIO'),
('PATEN', 'PATENTE DI GUIDA'),
('PATNA', 'PATENTE NAUTICA'),
('PORM5', 'PORTO D''ARMI GUARDIE GIUR'),
('PORM3', 'PORTO D''ARMI USO SPORTIVO'),
('PORM2', 'PORTO FUCILE DIF. PERSON.'),
('PORM1', 'PORTO FUCILE USO CACCIA'),
('PORM4', 'PORTO PISTOLA DIF. PERSON'),
('TENAV', 'TES. ENTE NAZ. ASSIS.VOLO'),
('TFEXD', 'TES. FERROV. EX DEPUTATI'),
('TFERD', 'TES. FERROVIARIA DEPUTATI'),
('TESPT', 'TES. POSTE E TELECOMUNIC.'),
('TECAM', 'TES. UNICO PER LA CAMERA'),
('TEDOG', 'TES.DOGANALE RIL.MIN.FIN.'),
('CFMIL', 'TESS. AG. E AG.SC. C.F.S.'),
('PPAGE', 'TESS. AGENTI/ASS.TI P.P.'),
('PSAPP', 'TESS. AGENTI/ASS.TI P.S.'),
('ACMIL', 'TESS. APP.TO AG.CUSTODIA'),
('CCMIL', 'TESS. APP.TO CARABINIERI'),
('GFMIL', 'TESS. APP.TO FINANZIERE'),
('VIMIL', 'TESS. APP.TO/VIG. URBANO'),
('VVMIL', 'TESS. APP.TO/VIG. VV.FF.'),
('TESCS', 'TESS. CONSIGLIO DI STATO'),
('TESCA', 'TESS. CORTE D''APPELLO'),
('TECOC', 'TESS. CORTE DEI CONTI'),
('TEFSE', 'TESS. FERROV. SENATO'),
('PSFUN', 'TESS. FUNZIONARI P.S.'),
('TETEL', 'TESS. IDENTIF.TELECOM IT.'),
('TEAMC', 'TESS. ISCR. ALBO MED/CHI.'),
('TEAOD', 'TESS. ISCRIZ. ALBO ODONT.'),
('PPISP', 'TESS. ISPETTORI P.P.'),
('PSISP', 'TESS. ISPETTORI P.S.'),
('TESEA', 'TESS. MEMBRO EQUIP. AEREO'),
('MMMIL', 'TESS. MILIT. M.M.'),
('SDMIL', 'TESS. MILIT. TRUPPA SISMI'),
('EIMIL', 'TESS. MILITARE E.I.'),
('TENAT', 'TESS. MILITARE NATO'),
('AMMIL', 'TESS. MILITARE TRUPPA A.M'),
('TESAE', 'TESS. MIN. AFFARI ESTERI'),
('TESMB', 'TESS. MIN.BEN.E ATT.CULT.'),
('TEMPI', 'TESS. MIN.PUBB.ISTRUZIONE'),
('TESMN', 'TESS. MINIST. TRASP/NAVIG'),
('TESMD', 'TESS. MINISTERO DIFESA'),
('TESMF', 'TESS. MINISTERO FINANZE'),
('TESMG', 'TESS. MINISTERO GIUSTIZIA'),
('TESMI', 'TESS. MINISTERO INTERNO'),
('TESLP', 'TESS. MINISTERO LAVORI PU'),
('TESMS', 'TESS. MINISTERO SANITA'''),
('TESMT', 'TESS. MINISTERO TESORO'),
('TESOG', 'TESS. ORDINE GIORNALISTI'),
('PARLA', 'TESS. PARLAMENTARI'),
('MAGIS', 'TESS. PERS. MAGISTRATI'),
('GFTRI', 'TESS. POL. TRIB. G.D.F.'),
('PSFEM', 'TESS. POLIZIA FEMMINILE'),
('TESPC', 'TESS. PRES.ZA CONS. MIN.'),
('TESPI', 'TESS. PUBBLICA ISTRUZIONE'),
('DESIS', 'TESS. S.I.S.D.E.'),
('ACSOT', 'TESS. SOTT.LI AG.CUSTODIA'),
('GFSOT', 'TESS. SOTT.LI G.D.F.'),
('VISOT', 'TESS. SOTT.LI VIG. URBANI'),
('VVSOT', 'TESS. SOTTUFF.LI VV.FF.'),
('AMSOT', 'TESS. SOTTUFFICIALI A.M.'),
('CCSOT', 'TESS. SOTTUFFICIALI CC'),
('EISOT', 'TESS. SOTTUFFICIALI E.I.'),
('SDSOT', 'TESS. SOTTUFFICIALI SISMI'),
('CFSOT', 'TESS. SOTTUFICIALI C.F.S.'),
('MMSOT', 'TESS. SOTTUFICIALI M.M.'),
('PPSOV', 'TESS. SOVRINTENDENTI P.P.'),
('PSSOT', 'TESS. SOVRINTENDENTI P.S.'),
('ACUFF', 'TESS. UFF.LI AG.CUSTODIA'),
('VIUFF', 'TESS. UFF.LI VIG.URBANI'),
('CCUFF', 'TESS. UFFICIALE'),
('AMUFF', 'TESS. UFFICIALI A.M.'),
('CFUFF', 'TESS. UFFICIALI C.F.S.'),
('EIUFF', 'TESS. UFFICIALI E.I.'),
('GFUFF', 'TESS. UFFICIALI G.D.F.'),
('MMUFF', 'TESS. UFFICIALI M.M.'),
('PPUFF', 'TESS. UFFICIALI P.P.'),
('PSUFF', 'TESS. UFFICIALI P.S.'),
('SDUFF', 'TESS. UFFICIALI SISMI'),
('VVUFF', 'TESS. UFFICIALI VV.FF.'),
('TESIN', 'TESS.ISCR. ALBO INGEGNERI'),
('TESAR', 'TESS.ISCR.ALBO ARCHITETTI'),
('TEPOL', 'TESS.MIN.POLIT.AGRIC.FOR.'),
('TESNO', 'TESSERA DELL''ORDINE NOTAI'),
('TESAV', 'TESSERA ISCR. ALBO AVVOC.'),
('TESDI', 'TESSERA RICONOSC. D.I.A.'),
('TESUN', 'TESSERA U.N.U.C.I.'),
('RIFUG', 'TITOLO VIAGGIO RIF.POLIT.')
ON CONFLICT DO NOTHING;

-- Facility Types (examples)
INSERT INTO host.facility_type (code, description) VALUES
('HOTEL', 'Hotel'),
('BB', 'Bed & Breakfast'),
('APART', 'Apartment'),
('AGRITU', 'Agriturismo'),
('HOSTEL', 'Hostel'),
('VILLA', 'Villa'),
('CAMPING', 'Camping')
ON CONFLICT DO NOTHING;

-- Tourist Tax Rates (from Italian regulations - Corteno Golgi example)
-- Note: Adjust 'amount' field based on actual municipality rates
INSERT INTO host.tourist_tax (code, description, amount) VALUES
('0000000001', '5.1b) Esenzione per i minori fino al compimento del dodicesimo anno di età', 0.00),
('0000000002', '5.1a) Esenzione per gli iscritti all''anagrafe dei residenti del Comune', 0.00),
('0000000003', '5.1c) Esenzione per gli accompagnatori turistici di gruppi di almeno 25 partecipanti, gli autisti dei bus che li trasportano e gli insegnanti in gita scolastica', 0.00),
('0000000004', '5.1d) Esenzione per il personale dipendente del gestore della struttura ricettiva che ivi svolge attività lavorativa', 0.00),
('0000000005', '_NESSUNA ESENZIONE (TARIFFA PIENA)', 2.50),
('0000000006', '5.1e) Esenzione per persone non autosufficienti munite di certificazione medica e relativo accompagnatore', 0.00),
('0000000007', '5.1f) Esenzione per i volontari coordinati dalla Protezione Civile che alloggiano in strutture ricettive a seguito di provvedimenti adottati da autorità pubbliche, per fronteggiare eventi calamitosi', 0.00),
('0000000008', '5.1g) Esenzione per personale appartenente alla Polizia di Stato e locale, alle altre forze armate, nonché al corpo nazionale dei vigili del fuoco che, per esigenze di servizio, soggiornano nel Comune e limitatamente al servizio medesimo', 0.00),
('0000000009', '5.1h) Esenzione per i beneficiari di soggiorni gratuiti, per tali intendendosi quelli per i quali il gestore della struttura ricettiva non percepisce corrispettivo né dall''alloggiato né da altri', 0.00)
ON CONFLICT DO NOTHING;

-- Note: The amount for code '0000000005' (standard rate) is set to €2.50 as an example.
-- Adjust this value according to your municipality's actual tourist tax rate.
